In [1]:
file=open("text","w")
file.write("hello,world")
file.close


<function TextIOWrapper.close()>

In [2]:
list1=[1,2,3]
list2=list1.copy()
list1.append(4)
print(list1)
print(list2)

[1, 2, 3, 4]
[1, 2, 3]


In [3]:
numbers=[1,2,3,4]
numbers.reverse()
print(numbers)

[4, 3, 2, 1]


In [4]:
text="hello"
reverse_text=text[::-1]
print(reverse_text)


olleh


In [5]:
reverse_text=text[:-1]
print(reverse_text)

hell


In [6]:
numbers=[1,2,3,3,4,5,6]
numbers.remove(3)
print(numbers)

[1, 2, 3, 4, 5, 6]


In [7]:
forward indexing;

SyntaxError: invalid syntax (3840648161.py, line 1)

In [1]:
my_list=['a','b','c','d','e']
print(my_list[0])
print(my_list[3])
print(my_list[4])

a
d
e


In [2]:
text="python"
print(text[0])
print(text[5])

p
n


In [ ]:
backward indexing;

In [3]:
my_list=['a','b','c','d','e']
print(my_list[-1])
print(my_list[-3])
print(my_list[-5])

e
c
a


In [4]:
text="python"
print(text[-1])
print(text[-5])

n
y


farward slicing;

In [5]:
my_list=['a','b','c','d','e','f','g']
print(my_list[1:4])
print(my_list[0:5])
print(my_list[2:])
print(my_list[:5])
print(my_list[:])


['b', 'c', 'd']
['a', 'b', 'c', 'd', 'e']
['c', 'd', 'e', 'f', 'g']
['a', 'b', 'c', 'd', 'e']
['a', 'b', 'c', 'd', 'e', 'f', 'g']


# backward slicing;

In [ ]:
my_list=['1','2','3','4','5','6','7','8']
my_list

In [6]:
my_list=(['1','2','3','4','5','6','7','8'])
my_list
print(my_list[-5:-1])

['4', '5', '6', '7']


step slicing;

In [7]:
my_list=['a','b','c','d','e','f','g','h']
my_list

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [8]:
print(my_list[3:6])

['d', 'e', 'f']


In [9]:
text="python"
print(text[1::3])
print(text[2::4])

yo
t


In [10]:
my_tuple=['10','20','30','40','50','60','70']
my_tuple

['10', '20', '30', '40', '50', '60', '70']

In [11]:
print(my_tuple[2::3])

['30', '60']


In [12]:
print(my_tuple[1::2])

['20', '40', '60']


In [13]:
print(my_tuple[0:5:2])

['10', '30', '50']


In [14]:
print(my_tuple[1:6:2])

['20', '40', '60']


In [15]:
bin(25)

'0b11001'

In [16]:
int(0b11001)

25

In [17]:
bin(35)

'0b100011'

In [18]:
int(0b100011)

35

In [19]:
oct(25)

'0o31'

In [20]:
int(0o31)

25

In [21]:
bin(7)

'0b111'

In [22]:
int(0b111)

7

In [23]:
0xa

10

In [24]:
0xb

11

In [25]:
hex(256)

'0x100'

In [26]:
hex(25)

'0x19'

In [27]:
0x19

25

In [28]:
a2=5
b2=6


a2,b2=b2,a2

In [ ]:
l1=[70.2.3,True,'1+2j',[1,2,3]]

In [ ]:
list sorting
python coding using cli
tuple
bitwise operator

In [29]:
l=[400,30,20]
l

[400, 30, 20]

In [53]:
l.sort()
print(l)

[20, 30, 400]


In [55]:
a=['z','a','m']
a.reverse()
print(a)


['m', 'a', 'z']


In [11]:
a=2
b=3
a+b

5

In [12]:
int.__add__(2,3)

5

In [14]:
int.__sub__(2,3)

-1

In [15]:
int.__mul__(2,3)

6

In [17]:
float.__sub__(3.3,2.2)

1.0999999999999996

# tuple

In [18]:
t=()
t
type(t)

tuple

In [19]:
t1=1,2,3
t1

(1, 2, 3)

In [20]:
t

(1, 2, 3)

In [76]:
t.count(2)
print(t)

NameError: name 't' is not defined

In [75]:
t1.index(2)

NameError: name 't1' is not defined

In [25]:
t1

(1, 2, 3)

In [77]:
t1(:2)

SyntaxError: invalid syntax (2341456336.py, line 1)

In [30]:
t1

(1, 2, 3)

In [ ]:
packet
module
function

In [39]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

# bitwise operators(&,|,^,~,<<,>>)

In [13]:
5&3

1

In [41]:
5|3

7

In [42]:
5^3

6

In [43]:
~5

-6

In [44]:
~6

-7

In [49]:
~10

-11

In [45]:
5<<1

10

In [46]:
5<<2

20

In [47]:
5>>1

2

In [48]:
5>>2

1

In [3]:
s2={200,3,1,100,10}
s2

{1, 3, 10, 100, 200}

In [4]:
s3={'m','n','h'}
s3

{'h', 'm', 'n'}

In [5]:
s2

{1, 3, 10, 100, 200}

In [8]:
s2.add(30)
print(s2)

{1, 3, 100, 200, 10, 30}


In [10]:
s3=s2.copy()
print(s3)

{1, 3, 100, 200, 10, 30}


In [11]:
s3.add(2)
print(s3)

{1, 2, 3, 100, 200, 10, 30}


In [12]:
s3.pop()
print(s3)

{2, 3, 100, 200, 10, 30}


In [13]:
s3.remove(30)
print(s3)

{2, 3, 100, 200, 10}


In [15]:
s3.pop()
print(s3)

{3, 100, 200, 10}


In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [14]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [ ]:
parameter(inbuild)(ml,dl)
hyperparameter(user change inbuilt parameter)
finetune in llm

In [26]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [28]:
np.ones(3)

array([1., 1., 1.])

In [29]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [38]:
np.random.rand(2,3)

array([[0.60434682, 0.39344956, 0.10456917],
       [0.73830953, 0.93446821, 0.55278786]])

In [40]:
np.random.rand(4)

array([0.27556979, 0.91548751, 0.39854873, 0.73501502])

In [41]:
np.random.rand(2,3)

array([[0.27979463, 0.13830837, 0.64140967],
       [0.22405111, 0.56779972, 0.12325617]])

In [43]:
np.random.randint(2,4)

3

In [47]:
np.random.randint(0,1)

0

In [49]:
np.random.randint(10,20,5)

array([12, 11, 14, 10, 13])

In [19]:
import numpy as np

In [20]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
sum_arr=np.add(arr1,arr2)
print("sum:",sum_arr)

sum: [11 22 33 44 55]


In [21]:
np.random.randint(20,30,2)

array([27, 23])